#!/usr/bin/env python3
"""Build the deterministic Lambda ZIP package from Python source files."""

import argparse
import sys
from pathlib import Path
from typing import Iterable
from zipfile import ZIP_STORED, ZipFile, ZipInfo


FIXED_TIMESTAMP = (1980, 1, 1, 0, 0, 0)


def _source_files(source_dir: Path) -> Iterable[Path]:
    return sorted(source_dir.glob("*.py"), key=lambda path: path.name)


def build_archive_bytes(source_dir: Path) -> bytes:
    """Return a stable archive containing sorted Python files at its root."""

    from io import BytesIO

    output = BytesIO()
    with ZipFile(output, mode="w", compression=ZIP_STORED) as archive:
        for source_file in _source_files(source_dir):
            info = ZipInfo(source_file.name, date_time=FIXED_TIMESTAMP)
            info.compress_type = ZIP_STORED
            info.create_system = 3
            info.external_attr = 0
            archive.writestr(info, source_file.read_bytes())
    return output.getvalue()


def _write_or_check(source_dir: Path, output_path: Path, check: bool) -> int:
    generated = build_archive_bytes(source_dir)
    if check:
        if not output_path.exists():
            print("package drift: output archive is missing", file=sys.stderr)
            return 1
        if output_path.read_bytes() != generated:
            print("package drift: output archive differs from generated bytes", file=sys.stderr)
            return 1
        return 0

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_bytes(generated)
    return 0


def main(argv=None) -> int:
    module_root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail when the package has drifted")
    parser.add_argument("--source-dir", type=Path, default=module_root / "src")
    parser.add_argument(
        "--output", type=Path, default=module_root / "account-kpi-export-lambda.zip"
    )
    args = parser.parse_args(argv)
    return _write_or_check(args.source_dir, args.output, args.check)


if __name__ == "__main__":
    raise SystemExit(main())
